### ISSUE TITLE
Is it possible to get an alphanumeric keyboard for <input> on Z10?

### ISSUE THREAD

**Issue by sonjz** [blackberry/bbUI.js#857]
Currently if I specify `<input type="text" id="fieldName"  />`, I will get the virtual alpha keyboard on the Z10.

This is a slight UI annoyance if you are asking your client to enter a confirmation number or postal code which require alphanumeric.  BB has the alphanumeric keyboard (password entry), but I'm at a loss as to how to trigger it from bbUI.js.  My dev contact at BB was also at a loss.

I also posted on SO, no response:
http://stackoverflow.com/questions/16202647/how-to-get-alphanumeric-keyboard-on-input-in-html5-bbui-js-for-blackberry-10

**Comment by jny01** [comment]
I just updated my Blackberry z10 to the latest bb OS 10.3.1 - works great - except one major problem! I can't use alphanumeric password feature and I cannot disable the STUPID buggy bs Simple Password! Good Job moronic Devs at BB! You call this improvement! Anyone know if there is any fix to this annoying retarded issue that makes zero sense as to why I cannot even disable Simple Password and not able to use Alphanumeric on the new BB OS 10.3.1? Any help would be greatly appreciated. Sorry for the bother but only if Devs were more responsible before putting out buggy-ass time wasting updates that cause more problems then the "improvements" they offer. If all else fails I will simple go back to the old BB OS. Unreal. Ty all for taking the time. Cheers!

**Comment by splatterb0y** [comment]
@jny01 Nice bump bro!
